/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;

import javax.swing.*;

public class Game extends javax.swing.JFrame {
    
    KeyBoardController keyBoardController;



    /**
     *
     *
     *
     *
     *
     * Creates new form Game
     *
     *
     *
     *
     *
     */



    public Game() {
        initComponents();
    }
    public void setKeyBoardController(KeyBoardController keyBoardController) {
        this.keyBoardController = keyBoardController;
        this.addKeyListener(keyBoardController);
    }
    HealthState healthState = new HealthState();
    ScoreState scoreState = new ScoreState();
    AmmoState ammoState =  new AmmoState();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GamePanel();
        Ammo = new javax.swing.JLabel();
        AmmoLabel = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        ScoreLabel = new javax.swing.JLabel();
        NewGame = new javax.swing.JButton();
        Health = new javax.swing.JLabel();
        Pause = new javax.swing.JButton();
        Healthlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        Ammo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ammo.setText("Ammo: ");

        NewGame.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NewGame.setText("New Game");
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });

        Health.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Health.setText("Health: ");

        Pause.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });

        Score.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Score.setText("Score:");

        ScoreLabel.setBackground(new java.awt.Color(255, 255, 255));
        AmmoLabel.setBackground(new java.awt.Color(255, 255, 255));
        Healthlabel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NewGame, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(Pause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Healthlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))


                                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))

                    .addComponent(Ammo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addContainerGap(88, Short.MAX_VALUE)));




        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pause, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(Score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Health, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(Healthlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Ammo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
                this.dispose();
                Game game2 = new Game();
                game2.setVisible(true);
                GamePanel panel = (GamePanel) game2.jPanel1;
                KeyBoardController kc = new KeyBoardController(new MovementObserver(panel.getCurrentgrid(), new GameStatusObserver(game2), new HealthState(), new ScoreState(), new AmmoState()));
                game2.setKeyBoardController(kc);

                game2.requestFocusInWindow();
                panel.paintComponent(panel.getGraphics());               
                Thread thread = new Thread(new Runnable(){                   
                    public void run(){                       
                        while(true){

                            game2.health();
                            game2.ammo();
                            game2.score();
                            panel.repaint();

                            try{
                                Thread.sleep(50);
                            }
                            catch(Exception e){
                                System.out.println("ERROR RUNNING");
                            }
                        }
                    }
                });
                thread.start();
                
                
                
    }//GEN-LAST:event_NewGameActionPerformed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
       
    }//GEN-LAST:event_PauseActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Game game = new Game();
                game.setVisible(true);
                GamePanel panel = (GamePanel) game.jPanel1;
                KeyBoardController kc = new KeyBoardController(new MovementObserver(panel.getCurrentgrid(), new GameStatusObserver(game), new HealthState(), new ScoreState(), new AmmoState()));
               
                game.setKeyBoardController(kc);
                
                game.requestFocusInWindow();
                panel.paintComponent(panel.getGraphics());
                Thread thread;
                thread = new Thread(new Runnable(){
                    public void run(){
                        while(true){
                          
                            game.health();
                            game.ammo();
                            game.score();
                            panel.repaint();
                           
                            try{
                                Thread.sleep(50);
                            }
                            catch(Exception e){
                                
                            }
                        }
                    }
                });
                thread.start();
                
              
        
            }
            
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ammo;



















    private javax.swing.JLabel Health;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel Healthlabel;
    private javax.swing.JLabel ScoreLabel;
    private javax.swing.JLabel AmmoLabel;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton Pause;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void removeListener() {
        this.removeKeyListener(keyBoardController);

    }

    public JLabel health()
    {
        this.Healthlabel.setText(""+healthState.getHealth());
        return Healthlabel;
    }

    public JLabel ammo()
    {
        this.AmmoLabel.setText(""+ammoState.getAmmostate());
        return AmmoLabel;
    }

    public JLabel score()
    {
        this.ScoreLabel.setText(""+scoreState.getScore());
        return ScoreLabel;
    }

    
   
    
    }

